### ISSUE TITLE
"Directions" for Google Maps

### ISSUE THREAD

**Issue by lmreisdorf** [CodePath-AND102-Group-12/FindingFresh#11]
Add button on marketDetailFragment

**Comment by heynicortiz** [comment]
Clicking the address on a marketDetailFragment intents to Google Maps navigation. Assuming each market has a proper/full address, it should successfully route to the address. Current listing of markets has incomplete addresses so it typically uses a "best guess" and starts navigating.

**Comment by lmreisdorf** [comment]
It's going to the latitude and longitude coordinates that I assigned in the
Geopoint. If you want to go directly to an address, that is a paid feature
of the Google Map API. Those do not currently match the made up address
that is listed. There is an issue for the next sprint to create the
markets, at which time, I figured it could be refined to whatever we decide
it should be.

**Comment by heynicortiz** [comment]
That'll be something else to add in for our market objects then too - but what I meant is that if you click on the address right now (under the market name, not in the map preview), it'll take you to Maps for navigation.

**Comment by lmreisdorf** [comment]
That's great! I'll update the addresses to match the latitude longitude so
that can show in the gif for this week.
