### ISSUE TITLE
Firestore data model and new location API to grab Lat/long from address

### ISSUE THREAD

**Issue by lmreisdorf** [CodePath-AND102-Group-12/FindingFresh#16]

**Comment by heynicortiz** [comment]
I just switched over the MarketDetailFragment to using a Geocoder to determine lat/long from the given address. Here's a snippet in case it's useful for other areas:

```
val geocoder = Geocoder(view?.context)
val geoCoderResults = geocoder.getFromLocationName(marketDetail?.address, 1)
val marketDetailLatitude = geoCoderResults.get(0).latitude
val marketDetailLongitude = geoCoderResults.get(0).longitude
```

**Comment by heynicortiz** [comment]
Firestore data model is now implemented for both Market Listing and Market Detail fragments, images are loading in correctly if available as well

The Map fragment shows the map marker accurately based on the address using geocoder
