### ISSUE TITLE
Create Market Item in Firebase

### ISSUE THREAD

**Issue by Coreyander** [CodePath-AND102-Group-12/FindingFresh#5]
- Create Market Item with Name, Image, Address, Phone Number, Categories, website, description, date/time
- Populate information

**Comment by lmreisdorf** [comment]
Add time and days
get rid of category

**Comment by lmreisdorf** [comment]
markets in Florida

**Comment by heynicortiz** [comment]
Just a note that to create more, you want to do it using the app. I can't find a way to add the image after the fact because then it gets a filetype in the name so it won't match up with the adapter later. If it's all done in the app, there should be no issue.

Right now we have six set up.

**Comment by heynicortiz** [comment]
Remade the ones I messed up images for and now we're set with 13 farmers markets throughout a local area
