### ISSUE TITLE
Calendar Filter

### ISSUE THREAD

**Issue by Coreyander** [CodePath-AND102-Group-12/FindingFresh#7]

**Comment by heynicortiz** [comment]
Currently pending on implementation of market objects. Added additional fields to adding a market so that it could be a little easier. Currently thinking about just checking for current date and displaying a list of markets with a date after that, sorted by days of week provided.

**Comment by heynicortiz** [comment]
Spinner selection functionality implemented, selecting new option of "All" will return to full list.

The day filter and name filter "can" work at the same time, but has unintended side effects with the Recycler View items/images displayed.
